### ISSUE TITLE
Is the `uri` field RFC3986 compliant?

### ISSUE THREAD

**Issue by koraa** [syntax-tree/mdast#28]
Hi; thanks for the great library :)

Now to the point:

Parsing the following markdown

```markdown
# Foo

Hello World [link](<foo
bar>)
```

I get the following MDAST (represented as YAML, position info stripped):

```yaml
type: root
children:
- type: heading
  depth: 1
  children:
  - type: text
    value: Foo
- type: paragraph
  children:
  - type: text
    value: "Hello World "
  - type: link
    title: ~
    url: "foo\nbar"
    children:
    - type: text
      value: link
```

The AST looks pretty much as expected; the newline in the link is handled by just including a newline (0x20) character in the string; which also seems alright, but caused some problems for us when using the AST, because we expected URLs to be RFC3986 compliant; RFC3986 mandates that most special characters be percent-encoded.

Is this expected behavior?

We specifically ran into this issue when using json-schema to validate our mdast; do you have any reccomendation on what the best way would be to validate whether a mdast is comliant?
